#!/usr/bin/env python3
"""
Restore the without-Coconut utterance set with Sidon.

The script reads the canonical utterance metadata generated by
`build_without_coconut_dataset.py`, loads each original waveform, and writes restored
audio to the canonical `shuffled_file` location under the repository root.
"""

from __future__ import annotations

import argparse
import csv
import logging
import os
from pathlib import Path

from huggingface_hub import hf_hub_download
from sidon.cleansing import extract_seamless_m4t_features
import soundfile
import torch
from torch.nn.utils.rnn import pad_sequence


logger = logging.getLogger(__name__)
DEFAULT_SIDON_CHECKPOINT_REPO = "sarulab-speech/sidon-v0.1"
DEFAULT_SIDON_CHECKPOINT_REVISION = "b3b02d8bbd55fdbc410e6e46e76ef95ace4fbf52"


def parse_args() -> argparse.Namespace:
    """
    Parse command line arguments.

    Returns:
        argparse.Namespace: Parsed arguments.
    """

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        default=".",
        help="Repository root that contains the derived metadata CSV.",
    )
    parser.add_argument(
        "--utterance-csv",
        default="data/utterance_set/pair_pool_metadata_without_coconut.csv",
        help="Utterance metadata CSV.",
    )
    parser.add_argument(
        "--feature-extractor",
        default="",
        help="Sidon TorchScript feature extractor checkpoint.",
    )
    parser.add_argument(
        "--decoder",
        default="",
        help="Sidon TorchScript decoder checkpoint.",
    )
    parser.add_argument(
        "--checkpoint-repo",
        default=DEFAULT_SIDON_CHECKPOINT_REPO,
        help="Hugging Face repository that provides Sidon TorchScript checkpoints.",
    )
    parser.add_argument(
        "--checkpoint-revision",
        default=DEFAULT_SIDON_CHECKPOINT_REVISION,
        help="Pinned Hugging Face revision that provides the Sidon checkpoints.",
    )
    parser.add_argument(
        "--feature-extractor-filename",
        default="feature_extractor_cuda.pt",
        help="Feature extractor filename inside the checkpoint repository.",
    )
    parser.add_argument(
        "--decoder-filename",
        default="decoder_cuda.pt",
        help="Decoder filename inside the checkpoint repository.",
    )
    parser.add_argument(
        "--hf-token",
        default="",
        help="Optional Hugging Face token used to download Sidon checkpoints.",
    )
    parser.add_argument(
        "--device",
        default="cuda",
        help="Inference device passed to Sidon.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=8,
        help="Number of utterances restored per batch.",
    )
    parser.add_argument(
        "--target-sample-rate",
        type=int,
        default=48000,
        help="Sample rate written to restored WAV files.",
    )
    parser.add_argument(
        "--skip-existing",
        action="store_true",
        help="Skip utterances whose restored WAV already exists.",
    )
    return parser.parse_args()


def resolve_checkpoint_path(
    candidate_path: str,
    checkpoint_repo: str,
    checkpoint_revision: str,
    filename: str,
    hf_token: str,
) -> str:
    """
    Resolve a Sidon TorchScript checkpoint path.

    Args:
        candidate_path (str): Explicit local checkpoint path override.
        checkpoint_repo (str): Hugging Face repository that hosts the checkpoint.
        checkpoint_revision (str): Pinned repository revision.
        filename (str): Checkpoint filename inside the repository.
        hf_token (str): Optional Hugging Face token.

    Returns:
        str: Local path to the resolved checkpoint.
    """

    if candidate_path != "":
        return str(Path(candidate_path).expanduser().resolve())

    auth_args: dict[str, str] = {}
    resolved_token = hf_token or os.environ.get("HF_TOKEN") or os.environ.get("HUGGINGFACE_TOKEN")
    if resolved_token:
        auth_args["token"] = resolved_token

    try:
        return hf_hub_download(
            repo_id=checkpoint_repo,
            revision=checkpoint_revision,
            filename=filename,
            **auth_args,
        )
    except Exception as ex:
        raise RuntimeError(
            "Failed to resolve a Sidon checkpoint. "
            f"checkpoint_repo: {checkpoint_repo}, checkpoint_revision: {checkpoint_revision}, filename: {filename}",
        ) from ex


def build_sidon_processor():
    """
    Build a minimal Sidon processor for inference-only restoration.

    Returns:
        type: A local `SpeechDenoisingProcessor`-compatible class.
    """

    class LocalSpeechDenoisingProcessor:
        """
        Run Sidon's TorchScripted feature extractor and decoder for inference.
        """

        def __init__(
            self,
            feature_extractor_path: str,
            decoder_path: str,
            device: str,
            chunk_seconds: float,
            target_sample_rate: int,
        ) -> None:
            if device == "auto":
                device = "cuda" if torch.cuda.is_available() else "cpu"
            self.device = torch.device(device)
            self.feature_extractor = torch.jit.load(
                feature_extractor_path,
                map_location=self.device,
            )
            self.decoder = torch.jit.load(
                decoder_path,
                map_location=self.device,
            )
            self.feature_extractor.eval()
            self.decoder.eval()
            self.chunk_samples = max(int(chunk_seconds * 16_000), 1_600)
            self.target_sample_rate = target_sample_rate

        def _prepare_waveform_batch(
            self,
            waveforms: list[torch.Tensor] | torch.Tensor,
            sample_rates: list[int],
        ) -> torch.Tensor:
            del sample_rates
            waveforms_padded = torch.zeros(
                len(waveforms),
                self.chunk_samples,
                dtype=torch.float32,
            )
            if isinstance(waveforms, torch.Tensor):
                copy_length = min(waveforms.shape[-1], self.chunk_samples)
                if waveforms.shape[-1] > self.chunk_samples:
                    logger.warning(
                        f"Input waveform was truncated. target_samples: {self.chunk_samples}",
                    )
                waveforms_padded[:, :copy_length] = waveforms[:, :copy_length]
                return waveforms_padded

            for index, waveform in enumerate(waveforms):
                if waveform.shape[-1] > self.chunk_samples:
                    logger.warning(
                        f"Input waveform was truncated. target_samples: {self.chunk_samples}",
                    )
                    waveform = waveform[: self.chunk_samples]
                waveforms_padded[index, : waveform.shape[-1]] = waveform
            return waveforms_padded

        @torch.inference_mode()
        def process_batch(
            self,
            waveforms: list[torch.Tensor] | torch.Tensor,
            sample_rates: list[int] | None = None,
            expected_lengths: list[int] | None = None,
        ) -> list[torch.Tensor]:
            if sample_rates is None:
                raise ValueError("sample_rates must be provided for Sidon restore.")
            if expected_lengths is None:
                expected_lengths = []
                for waveform, sample_rate in zip(waveforms, sample_rates):
                    duration_seconds = waveform.shape[-1] / float(sample_rate)
                    expected_lengths.append(
                        int(round(duration_seconds * self.target_sample_rate))
                    )

            prepared_waveforms = self._prepare_waveform_batch(
                waveforms,
                sample_rates,
            )
            features = extract_seamless_m4t_features(
                list(prepared_waveforms),
                return_tensors="pt",
                padding_value=1.0,
                device=str(self.device),
            )
            feature_tensor = self.feature_extractor(
                features["input_features"].to(self.device)
            )["last_hidden_state"]
            restored_waveforms = self.decoder(feature_tensor.transpose(1, 2)).cpu()

            results: list[torch.Tensor] = []
            for sample_index, sample in enumerate(restored_waveforms):
                restored_waveform = sample.view(-1)
                target_length = expected_lengths[sample_index]
                current_length = restored_waveform.shape[-1]
                if target_length > 0 and current_length != target_length:
                    diff = target_length - current_length
                    if diff > 0:
                        restored_waveform = torch.nn.functional.pad(
                            restored_waveform,
                            (0, diff),
                        )
                    elif diff < 0:
                        restored_waveform = restored_waveform[:target_length]
                results.append(restored_waveform.contiguous())

            return results

    return LocalSpeechDenoisingProcessor


def load_rows(utterance_csv: Path) -> list[dict[str, str]]:
    """
    Load utterance metadata rows.

    Args:
        utterance_csv (Path): Metadata CSV path.

    Returns:
        list[dict[str, str]]: Parsed rows.
    """

    with utterance_csv.open("r", encoding="utf-8", newline="") as file_pointer:
        return list(csv.DictReader(file_pointer))


def load_waveform(audio_path: Path) -> tuple[torch.Tensor, int]:
    """
    Load a waveform as mono float32 audio.

    Args:
        audio_path (Path): Input audio path.

    Returns:
        tuple[torch.Tensor, int]: Mono waveform and sample rate.
    """

    waveform_array, sample_rate = soundfile.read(
        str(audio_path),
        dtype="float32",
        always_2d=True,
    )
    waveform = torch.from_numpy(waveform_array).transpose(0, 1)
    if waveform.size(0) > 1:
        waveform = waveform.mean(dim=0, keepdim=True)
    return waveform.squeeze(0).to(dtype=torch.float32), int(sample_rate)


def save_waveform(output_path: Path, waveform: torch.Tensor, sample_rate: int) -> None:
    """
    Save a mono waveform to a WAV file.

    Args:
        output_path (Path): Destination WAV path.
        waveform (torch.Tensor): Mono waveform.
        sample_rate (int): Output sample rate.
    """

    output_path.parent.mkdir(parents=True, exist_ok=True)
    soundfile.write(
        str(output_path),
        waveform.detach().cpu().numpy(),
        sample_rate,
        subtype="PCM_16",
    )


def process_batch(
    processor,
    repo_root: Path,
    batch_rows: list[dict[str, str]],
    target_sample_rate: int,
) -> None:
    """
    Restore a batch of utterances and write the outputs.

    Args:
        processor: Sidon batch processor instance.
        repo_root (Path): Repository root.
        batch_rows (list[dict[str, str]]): Batch rows.
        target_sample_rate (int): Output sample rate.
    """

    waveforms: list[torch.Tensor] = []
    sample_rates: list[int] = []
    output_paths: list[Path] = []
    expected_lengths: list[int] = []

    for row in batch_rows:
        input_path = repo_root / row["original_file"].removeprefix("./")
        output_path = repo_root / row["shuffled_file"]
        waveform, sample_rate = load_waveform(input_path)
        waveforms.append(waveform)
        sample_rates.append(sample_rate)
        output_paths.append(output_path)
        expected_lengths.append(
            int(round(waveform.numel() / float(sample_rate) * target_sample_rate))
        )

    padded_waveforms = pad_sequence(waveforms, batch_first=True)
    restored_waveforms = processor.process_batch(
        waveforms=padded_waveforms,
        sample_rates=sample_rates,
        expected_lengths=expected_lengths,
    )

    for output_path, restored_waveform in zip(output_paths, restored_waveforms):
        save_waveform(output_path, restored_waveform, target_sample_rate)


def main() -> None:
    """
    Restore all utterances listed in the derived metadata CSV.
    """

    args = parse_args()
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    repo_root = Path(args.repo_root).resolve()
    utterance_csv = (repo_root / args.utterance_csv).resolve()
    feature_extractor_path = resolve_checkpoint_path(
        candidate_path=args.feature_extractor.strip(),
        checkpoint_repo=args.checkpoint_repo,
        checkpoint_revision=args.checkpoint_revision,
        filename=args.feature_extractor_filename,
        hf_token=args.hf_token.strip(),
    )
    decoder_path = resolve_checkpoint_path(
        candidate_path=args.decoder.strip(),
        checkpoint_repo=args.checkpoint_repo,
        checkpoint_revision=args.checkpoint_revision,
        filename=args.decoder_filename,
        hf_token=args.hf_token.strip(),
    )

    SpeechDenoisingProcessor = build_sidon_processor()
    processor = SpeechDenoisingProcessor(
        feature_extractor_path=feature_extractor_path,
        decoder_path=decoder_path,
        device=args.device,
        chunk_seconds=30.0,
        target_sample_rate=args.target_sample_rate,
    )

    rows = load_rows(utterance_csv)
    pending_rows: list[dict[str, str]] = []
    for row in rows:
        output_path = repo_root / row["shuffled_file"]
        if args.skip_existing is True and output_path.exists() is True:
            continue
        pending_rows.append(row)

    print(f"Total utterances listed: {len(rows)}")
    print(f"Pending utterances to restore: {len(pending_rows)}")

    failed_batch_starts: list[int] = []

    for batch_start in range(0, len(pending_rows), args.batch_size):
        batch_rows = pending_rows[batch_start : batch_start + args.batch_size]
        batch_end = batch_start + len(batch_rows)
        try:
            process_batch(
                processor=processor,
                repo_root=repo_root,
                batch_rows=batch_rows,
                target_sample_rate=args.target_sample_rate,
            )
            print(f"Restored utterances: {batch_end}/{len(pending_rows)}")
        except Exception as ex:
            logger.exception(
                f"Failed to restore batch. progress: {batch_end}/{len(pending_rows)}",
                exc_info=ex,
            )
            failed_batch_starts.append(batch_start)
            continue

    if len(failed_batch_starts) > 0:
        raise RuntimeError(
            "Sidon restore finished with failed batches. "
            f"failed_batch_count: {len(failed_batch_starts)}, "
            f"failed_batch_starts: {failed_batch_starts[:20]}",
        )


if __name__ == "__main__":
    main()
